services:
  postgres:
    image: postgres:15-alpine
    container_name: crm-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-crm}
      POSTGRES_USER: postgres
    volumes:
      - .docker/volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crm"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: crm-app
    ports:
      - "3001:3000"
      - "5555:5555"
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-crm}?sslmode=disable
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/.next
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

  redis:
    image: redis:7-alpine
    container_name: crm-redis
    ports:
      - "6379:6379"
    volumes:
      - .docker/volumes/redis:/data
    command: redis-server --appendonly yes

networks:
  default:
    name: crm-network
